name: precoding_quiz
description: Quiz game about Programming Subjects, like Python, Java, C++, JavaScript.

publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.22.0
  google_fonts: ^1.1.0
  http: ^0.12.2
  get: ^4.1.4
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/spinner.gif

  fonts:
    - family: Quando
      fonts:
        - asset: assets/fonts/Quando.ttf
    - family: Alike
      fonts:
        - asset: assets/fonts/Alike-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy.ttf
